# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98eba3b3a8ec1eb5e8c6b709a552b30dc768ed52b68ee322eb547e0ff628ab3ed4dc34c4ea5e906995acf68c9e08689f911862ef0adfd037012400609e8b94ed

test:
  secret_key_base: db2947f7c7fb7df8324bb4705071873da76552be20d585b9baab1bc88b5f4e0ef6522940871479aeb9b982a69c62891be621a84623a07c6519d8a078a9d77809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
